version: "3.9"
services:
  cloud-iot-paas-broker:
    image: "eclipse-mosquitto:2.0.15"
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"
      
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cloud-iot
      MONGO_INITDB_ROOT_PASSWORD: asDDffb
    volumes:
      - mongodb-data:/data/db
      
volumes:
  mongodb-data: